// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaApp.Data;

#nullable disable

namespace PizzaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IngredientPizza", b =>
                {
                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PizzasId")
                        .HasColumnType("uuid");

                    b.HasKey("IngredientsId", "PizzasId");

                    b.HasIndex("PizzasId");

                    b.ToTable("IngredientPizza");
                });

            modelBuilder.Entity("PizzaApp.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("UserType").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PizzaApp.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("text");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PizzaApp.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("PizzaApp.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            CountryId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Warszawa",
                            Region = "Mazowieckie"
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            CountryId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Kraków",
                            Region = "Małopolskie"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CountryId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Gdańsk",
                            Region = "Pomorskie"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CountryId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Wrocław",
                            Region = "Dolnośląskie"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CountryId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Poznań",
                            Region = "Wielkopolskie"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CountryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Rzym",
                            Region = "Lacjum"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CountryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Neapol",
                            Region = "Kampania"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CountryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Mediolan",
                            Region = "Lombardia"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CountryId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "Nowy Jork",
                            Region = "Nowy Jork"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CountryId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "Chicago",
                            Region = "Illinois"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CountryId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "Berlin",
                            Region = "Berlin"
                        });
                });

            modelBuilder.Entity("PizzaApp.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhonePrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            IsoCode = "PL",
                            Name = "Polska",
                            PhonePrefix = "+48"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsoCode = "IT",
                            Name = "Włochy",
                            PhonePrefix = "+39"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsoCode = "US",
                            Name = "Stany Zjednoczone",
                            PhonePrefix = "+1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            IsoCode = "DE",
                            Name = "Niemcy",
                            PhonePrefix = "+49"
                        });
                });

            modelBuilder.Entity("PizzaApp.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAllergen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMeat")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("PizzaApp.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PizzeriaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PizzeriaId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("PizzaApp.Entities.Pizza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseSauce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("DiameterCm")
                        .HasColumnType("double precision");

                    b.Property<string>("Dough")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Kcal")
                        .HasColumnType("double precision");

                    b.Property<double>("LengthCm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thickness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("double precision");

                    b.Property<double>("WidthCm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzaApp.Entities.Pizzeria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<int>("AveragePreparationTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DeliveryCost")
                        .HasColumnType("numeric");

                    b.Property<double>("MaxDeliveryRange")
                        .HasColumnType("double precision");

                    b.Property<decimal>("MinOrderAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BrandId");

                    b.ToTable("Pizzerias");
                });

            modelBuilder.Entity("PizzaApp.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PizzeriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PizzeriaId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("PizzaApp.Entities.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("PizzeriaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PizzeriaId");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("PizzaPromotion", b =>
                {
                    b.Property<Guid>("PizzasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromotionsId")
                        .HasColumnType("uuid");

                    b.HasKey("PizzasId", "PromotionsId");

                    b.HasIndex("PromotionsId");

                    b.ToTable("PromotionPizza", (string)null);
                });

            modelBuilder.Entity("PizzaApp.Entities.Customer", b =>
                {
                    b.HasBaseType("PizzaApp.Entities.Account");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.HasIndex("AddressId");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("PizzaApp.Entities.Owner", b =>
                {
                    b.HasBaseType("PizzaApp.Entities.Account");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("IngredientPizza", b =>
                {
                    b.HasOne("PizzaApp.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApp.Entities.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Entities.Address", b =>
                {
                    b.HasOne("PizzaApp.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PizzaApp.Entities.Brand", b =>
                {
                    b.HasOne("PizzaApp.Entities.Owner", "Owner")
                        .WithMany("Brands")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PizzaApp.Entities.City", b =>
                {
                    b.HasOne("PizzaApp.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PizzaApp.Entities.Menu", b =>
                {
                    b.HasOne("PizzaApp.Entities.Pizzeria", null)
                        .WithMany("Menus")
                        .HasForeignKey("PizzeriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Entities.Pizza", b =>
                {
                    b.HasOne("PizzaApp.Entities.Menu", null)
                        .WithMany("Pizzas")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Entities.Pizzeria", b =>
                {
                    b.HasOne("PizzaApp.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApp.Entities.Brand", "Brand")
                        .WithMany("Pizzerias")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PizzaApp.Entities.Promotion", b =>
                {
                    b.HasOne("PizzaApp.Entities.Pizzeria", "Pizzeria")
                        .WithMany("Promotions")
                        .HasForeignKey("PizzeriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizzeria");
                });

            modelBuilder.Entity("PizzaApp.Entities.WorkSchedule", b =>
                {
                    b.HasOne("PizzaApp.Entities.Pizzeria", "Pizzeria")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("PizzeriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizzeria");
                });

            modelBuilder.Entity("PizzaPromotion", b =>
                {
                    b.HasOne("PizzaApp.Entities.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaApp.Entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaApp.Entities.Customer", b =>
                {
                    b.HasOne("PizzaApp.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PizzaApp.Entities.Brand", b =>
                {
                    b.Navigation("Pizzerias");
                });

            modelBuilder.Entity("PizzaApp.Entities.Menu", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("PizzaApp.Entities.Pizzeria", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Promotions");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("PizzaApp.Entities.Owner", b =>
                {
                    b.Navigation("Brands");
                });
#pragma warning restore 612, 618
        }
    }
}
